backend:
  name: github
  repo: anfilive/37eight-site
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "blog"
    label: "Статьи"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Заголовок (H1)", name: "title", widget: "string" }
      - { label: "Описание для превью", name: "description", widget: "string" }
      - { label: "Дата", name: "publishDate", widget: "datetime" }
      - { label: "SEO Title", name: "seo_title", widget: "string", required: false }
      - { label: "Текст статьи", name: "body", widget: "markdown" }
      - { label: "Макет", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro" }
